a = input('Digite algo: ')
print(type(a))
print('numeric', a.isnumeric())
print('alpha', a.isalpha())
print('alnum', a.isalnum())
print('upper', a.isupper())
print('lower', a.islower())
print('space', a.isspace())
print('capital', a.isupper())
print('decimal', a.isdecimal())
print('ascii', a.isascii())