nome = str(input('Digite seu nome completo: ')).strip()
print('[Analisando o seu nome...]')
print(nome.upper())
print(nome.lower())
print(len(nome)-nome.count(' '))
print(nome.find(' '))
separa = nome.split()
print(len(separa[0]))